"use client";
import { Inter } from "next/font/google";
import "@flaticon/flaticon-uicons/css/regular/rounded.css";
import "@flaticon/flaticon-uicons/css/solid/rounded.css";
import "./globals.css";
import localFont from "@next/font/local";
import Cookies from "js-cookie";
import { redirect, usePathname } from "next/navigation";
import { useEffect } from "react";
const iransans = localFont({
  src: [
    {
      path: "../../public/fonts/iransans/ttf/IRANSansWeb(FaNum).ttf",
    },
  ],
  variable: "--font-iransans",
});
const fedra = localFont({
  src: [
    {
      path: "../../public/fonts/fedra/fedra.ttf",
    },
  ],
  variable: "--font-fedra",
});

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  const path = usePathname();
  useEffect(()=>{
    const token = Cookies.get("token");
    if (!path.includes("auth")) {
      if (!token){console.log("here1"); redirect("/pages/auth")};
      if (token.length == 0){console.log("here2"); redirect("/pages/auth")};
    }
  } , [])
  

  return (
    <html lang="en">
      <body className={iransans.variable}>{children}</body>
    </html>
  );
}
